---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: aks-helloworld
spec:
  selector:
    matchLabels:
      app: aks-helloworld
      #role: follower
      #tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: aks-helloworld
        #role: follower
        #tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
