apiVersion: v1
kind: Namespace
metadata:
  name: aks-helloworld
---
apiVersion: v1
kind: Pod
metadata:
  name: aks-helloworld
  namespace: aks-helloworld
  labels:
    app: aks-helloworld
spec:
  containers:
  - image: "mcr.microsoft.com/azuredocs/aks-helloworld:v1"
    name: aks-helloworld-image
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: aks-helloworld
spec:
  selector:
    app: aks-helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
 type: LoadBalancer
