---
apiVersion: v1
kind: Pod
metadata:
  name: aks-helloworld
  labels:
    app: aks-helloworld
spec:
  containers:
  - image: "mcr.microsoft.com/azuredocs/aks-helloworld:v1"
    name: aks-helloworld-image
    ports:
    - containerPort: 80
      protocol: TCP
