apiVersion: v1
kind: Namespace
metadata:
  name: arc-k8s-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: arc-k8s-demo
  namespace: arc-k8s-demo
  labels:
    app: arc-k8s-demo
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: arc-k8s-demo-image
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: arc-k8s-demo
  namespace: arc-k8s-demo
  labels:
    name: arc-k8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: arc-k8s-demo
