---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
  namespace: crud-app-bitcoin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
     containers:
     - name: bitcoin
       image: unnamed22090/bitcoin_api
       ports:
       - containerPort: 80
       resources:
         requests:
            cpu: 128m
            memory: 512Mi
         limits:
            cpu: 256m
            memory: 1G
         env:
         - name: TZ
           value: "Asia/Bangkok"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: crud-app-bitcoin
spec:
  selector:
    app: mongo-express
  # type: LoadBalancer
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
      targetPort: 8081
---
apiVersion: v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: crud-app-bitcoin
  labels:
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - name: mongo-express
          containerPort: 8081
          protocol: TCP
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "root"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "1w2q3e4r5t6y"
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://root:1w2q3e4r5t6y@mongo-service.crud-app-bitcoin.svc.cluster.local:27017/"
---
apiVersion: v1
kind: Deployment
metadata:
  name: mongo
  namespace: crud-app-bitcoin
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "1w2q3e4r5t6y"
